import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
      <title>Sparrowai</title>
      <meta name="description" content="AI-Powered Website Code Creation, By using  Gemini technologies to generate highly available code, it supports web (React, Vue, Tailwind CSS, shadcn/ui), native (react native) and other codes. It is generated using GPT-4 Vision. Code is generated by taking screenshots, drawing drafts, and inputting ideas."/>
      <meta name="robots" content="index, follow"/>
      <meta property="og:locale" content="en_US" />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="Sparrowai - AI-Powered Website component generator" />
      <meta property="og:description" content="Streamline web design with www.ancodeai.com: Convert ideas and images to HTML code instantly using AI, with Tailwind, React, and Vue support." />
      <meta property="og:url" content="https://sparrowai.vercel.app/" />
      <meta property="og:site_name" content="Sparrowai" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Sparrow - AI-Powered Website Code Creation" />
      <meta name="twitter:description" content="Streamline web design with https://sparrowai.vercel.app/: Convert ideas and images to HTML code instantly using AI, with Tailwind, React, and Vue support." />
      <script id="inline-script" dangerouslySetInnerHTML={{ __html: `window.EXCALIDRAW_ASSET_PATH = "/"` }} />
      <script defer data-domain="ancodeai.com" data-api="/plausible/api/event" src="/plausible/js/script.js"></script>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
